apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: airport
spec:
  database: airlinedb
  name: airport
  schema:
    mysql:
      primaryKey: [code]
      columns:
        - name: code
          type: char(4)
        - name: name
          type: varchar(255)
          constraints:
            notNull: true
