apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql
  namespace: default
spec:
  encryptedData:
    uri: AgAUvQTUyzvoyjGqPfifTRLpmOL4hLyisYAEDTwOSutND8kkuuGkVJHLv3rv5YZrdCGZwhAUxqcR5Tz4beZv1fQ28jmtklpt/nqklGmYzrE45H+/s07lxyXhLCJTaPhlrSf7+D94ZUxDkPcC29BWHvixlNk07ZJk+jf2ZCPGXgeTy56lYKTS33l34F6D0r2qQnPhXP3TDeqS6bzu1bNgOP5SAFCmqAF8Zfmt5jhb0rjtO3UoHV/v59Vquvn6zf8v40HggjYN5iSmgeJFrO17x5LWWYHEzupCUXxg0hUTWqKAawlDGeVRjMh3mFZ/1OR3sUDFxsQRBBM2oy/T+YmmANIACfR2JdF6L1ZiJxEJoD9FqDDr/zDtLleD++bCp3BrUjibdeV0noNLRzJq4mWGVGInZuc+yUqUO7XB8tttEskqpK/vaXNDBJceyPwyy7KZoUI8wEDWcPRN2JyaUdRN3NxCSMqwINFoXQHKno0UnxTjzpVbN70mcZ/n+LSM8Ha/+ecssFWYE96S2Jf3JlnvK7FwH91ER3TF+N2fgj/tUBNRvjE3wZpANwkDrLTHAEHMkhzCThlrgIEcGWfWSdY1gCAYc5DlcQ8lKJ1PT/IWpj9AiPvIHd0xBkfltEcBjdIgcufkDLpe0ExW+ocQhqBwO3uWEmoFi9IQQaokehFG1Kmt+nkGCvm/N+jOx7cJgIgU/820uM8DkOFet9+x61cgbGBSgGc25EhqUV8rollucUGOIcaGRC/bISwpbF31e17b5XJgETepSMXPBClJpUIgDlZzhDANxcO3AZxgyVyO4hL9exhL+VWp2bkM0fKw7EIAhAkENbNQVYmEyOWP7ms4wyNW6Jw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql
      namespace: default
    type: Opaque

