apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql
  namespace: default
spec:
  encryptedData:
    uri: AgA4QVfasrcygfrWG7L4oV8n6cCfar5OjUn4hLKYjx+OcykzhUia/1l2rp2vkmYsS4L766tS/U4mouCMJLL5FwjJXhHVcn8e1iyX24rCUiutKUtwBXFgoOROfjdz+IfhtTWD9IvICzUBTdwLmVB/m16r9ZCrW4Nnfq7kNX+3AMyal1KtLSl4v9UV0vZGTtvSwjEXEb3STBER/DnMS7pfb8Q7du+LBrWPFdOF/W/JfL6TLypw2rkxOqX2/Fq006OeLH70LR8ySTUJmBSW+Wk4DsYZKHdsaILHRPiiGu5ap1DJcDJftr6h6tUeeGiIfMFdR5mGyey+kPTuEEkvuv2TypGW53nbQsxviHO+3sW/HZncnM/PZzZxxot1+OCNpwlzq0U+8fjxyQnXdW/wsVm1eikKcGmVPcEVe97f9QJbd1YAJ89juq+dNdIkEv0ZfYsU2AvX1tdkkzPx3PeU0Ss64IjEk5MrCe7VQa99eTIiWf8pBuPk81XBdQjqccgt5X2PSHmPP9WKwkkDRQC7UxG8+u1e5aGsjzK7jUkM6AIuScFWrvuq7S2gDGWHWyLIj9YrH98n6wOShHV0jkr8QAeVgkWyAqgDp64usI5YUxd5BFitgdy4rOBXDzLY9OmC2SL43Gr2ASG/ypT2uwIomjcrvXVbFVkuhbNzPykaYZXmmkKYQZw+/u8OirrkQHWQO/3q2vPBedl6i1dph573hGIH4W0PkKBZXd11NvcyXDmZt6KnL7ld3ZNxQ00sUO9b0on1xq6oAb38+y0i15pBqIRgW3N8jU2U0fQths5ZreYe/uV4qPwDvCYb1+/XiMr1k5rzWFhLN0EBhkcheTUSsA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql
      namespace: default
    type: Opaque

