apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql
  namespace: default
spec:
  encryptedData:
    uri: AgBsKbyaHO6a4xPFpF8itINryKRjXiqCGXMstox6XMiGv7qepBFlApMhIeeG2aVI+Kyff0kMsQkEBU1VhpZ8Z3QW6PM1ShEdJeo0+6k91/I08CSA7r2sCxADsGosbBsrMYRZJo0SA70NVBjE0YKJmoGrSFsGVm2rCR9BCVE8z0b5PzMOf4oWMEbT2CPMJrNbeQ4niNQGPdtQaLnEfPSwOyrNJs3hT4qb2uKYqb3LOsmvCEpdIZhUFopXlubbF4e6nB/H0YoH6Wa7Nw1o0zvV4hyTNLO7vHxisSzYr03jXq6iAKxuZNVlGRU/wS05zPAuOWa1YrPamp8EtYhNlo0ctlQI2Aq/hqU4jdP2n4MKYHphGOdAEtPI54JEb4Bxv/+ULcmOltS5DVFfhpa/UV3AC6J7oTWarthf/OfGJQrrwnquaO/PiGyUbyD93Vn7iCoPY6dobK0WnzvhZHNJ1i+6CBIqDtvRVnvZcVwHS7/Pa5KHwR2snB1Tx2UFHUVYJQMVx4GZyAzqxytbNFS93fsf12aSQO7OG348/4bmIT7rWFQYgl+AVfT7aXscQKGLytHJNYbvixY6pKseaHNZIJ/Aj+ItqPEuX48Sd3qBi5jzQfWOT9cddI6L78FUGrrZ7am3F4kRXU3NsZQrZEXDtUoq2ccIRBQM7BoEXOlsrMcZUsKO3Lyq2zdKbl4cIZL40ILGl7wddfYDT9dgUUH9O5yz/e6CzHwifu7A/soqUxYNBYClw0dFpGsj3VjaranBfSWObwtDqPU0a+c7pCWMBGrZDiE7MxfucnYI2oeyhxpqmm6fRIGVXJTFqj8A/32RguGPqpLwAdVsyckv1fIHGpHGaF7mEfA0dUwyUw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql
      namespace: default
    type: Opaque

