apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealedsecrets
  namespace: default
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealedsecrets
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '2.1.1'
      sourceRef:
        kind: HelmRepository
        name: sealedsecrets
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
