apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: airlinedb
spec:
  immediateDeploy: true
  enableShellCommand: true
  deploySeedData: true
  connection:
    mysql:
      uri:
        valueFrom:
          secretKeyRef:
            name: mysql
            key: uri
